networks:
  traefik-public:
    external: true
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stage-flow-tools
    environment:
      - NUXT_JWT_SECRET=${NUXT_JWT_SECRET}
    image: stage-flow-tools
    labels:
      - traefik.enable=true
      - traefik.http.routers.stage-flow-tools.rule=Host(`quiz.your-domain.com`)
      - traefik.http.routers.stage-flow-tools.entrypoints=websecure
      - traefik.http.services.stage-flow-tools.loadbalancer.server.port=3000
      - traefik.http.routers.stage-flow-tools.tls.certresolver=myresolver

    networks:
      - traefik-public
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./.data/db:/app/.data/db
version: "3.9"
