networks:
  traefik-public:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stage-flow-tools
    container_name: stage-flow-tools
    restart: unless-stopped
    # Choose one and uncomment:
    # env_file:
    #   - .env
    # environment:
    #   - NUXT_JWT_SECRET=...
    #   - ...
    volumes:
      - ./data:/app/.data
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.services.stage-flow-tools.loadbalancer.server.port=3000
      - traefik.http.routers.stage-flow-tools.rule=Host(`quiz.your-domain.com`)
      - traefik.http.routers.stage-flow-tools.entrypoints=websecure
      - traefik.http.routers.stage-flow-tools.tls.certresolver=myresolver
      - traefik.http.middlewares.stage-flow-tools-cors.headers.accesscontrolalloworiginlist=http://localhost:3030
      - traefik.http.middlewares.stage-flow-tools-cors.headers.accesscontrolallowmethods=GET,POST,OPTIONS
      - traefik.http.middlewares.stage-flow-tools-cors.headers.accesscontrolallowheaders=Authorization,Content-Type
      - traefik.http.middlewares.stage-flow-tools-cors.headers.addvaryheader=true
      - traefik.http.routers.stage-flow-tools.middlewares=stage-flow-tools-cors
