import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptPath = fileURLToPath(import.meta.url)
const repoRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
const noticesManualCommand = 'vp run notices:generate'
const noticesTrackedOutput = 'THIRD_PARTY_NOTICES.md'
export const commitMessageHookMarker = 'stage-flow-tools-conventional-commit-hook'
export const noticesTriggerInputs = [
  'package.json',
  'pnpm-lock.yaml',
  'pnpm-workspace.yaml',
  'scripts/write-third-party-notices.ts',
]
export const noticesTriggerPattern = noticesTriggerInputs
  .map(path => path.replaceAll('.', '\\.'))
  .join('|')
const noticesTriggerArguments = noticesTriggerInputs.join(' ')

export const noticesHookMarker = 'stage-flow-tools-third-party-notices-hook'

export type NoticeHookPaths = {
  hookDispatcherRoot: string
  hooksRoot: string
  commitMessageHook: string
  preCommitDispatcher: string
  preCommitHook: string
}

export type NoticeHookStatusCheck = {
  ok: boolean
  text: string
}

const createNoticeHookPaths = (root: string): NoticeHookPaths => {
  const hooksRoot = resolve(root, '.vite-hooks')
  const hookDispatcherRoot = resolve(hooksRoot, '_')

  return {
    commitMessageHook: resolve(hooksRoot, 'commit-msg'),
    hookDispatcherRoot,
    hooksRoot,
    preCommitDispatcher: resolve(hookDispatcherRoot, 'pre-commit'),
    preCommitHook: resolve(hooksRoot, 'pre-commit'),
  }
}

const readTextIfExists = (path: string): string => (
  existsSync(path) ? readFileSync(path, 'utf8') : ''
)

export const assertVitePlusHooksInstalled = (root = repoRoot): void => {
  const paths = createNoticeHookPaths(root)

  if (existsSync(paths.preCommitDispatcher)) {
    return
  }

  throw new Error([
    'Vite+ pre-commit dispatcher is missing.',
    'Run `vp run hooks:install:vite-plus` first,',
    'or run `vp run hooks:install` to install Vite+ and third-party notice hooks.',
    `Missing: ${paths.preCommitDispatcher.replace(`${root}/`, '')}`,
  ].join('\n'))
}

export const preCommitHookContent = (): string => `#!/bin/sh
# ${noticesHookMarker}: pre-commit
# Generated by: vp run notices:hook:install
# Refreshes third-party notices before Vite+ staged checks.
run_staged() {
    vp staged
}

GIT_DIR=$(git rev-parse --git-dir 2>/dev/null) || exit 0
if [ -d "$GIT_DIR/rebase-merge" ] \\
    || [ -d "$GIT_DIR/rebase-apply" ] \\
    || [ -f "$GIT_DIR/MERGE_HEAD" ] \\
    || [ -f "$GIT_DIR/CHERRY_PICK_HEAD" ]; then
    run_staged
    exit $?
fi

STAGED=$(git diff --cached --name-only --diff-filter=ACDMRTUXB)
if [ -z "$STAGED" ]; then
    run_staged
    exit $?
fi

# Third-party notice triggers: ${noticesTriggerInputs.join(' ')}
NOTICE_TRIGGER=$(echo "$STAGED" | grep -E '^(${noticesTriggerPattern})$' || true)
UNSTAGED_TRIGGER=$(git diff --name-only -- ${noticesTriggerArguments} | grep -E '^(${noticesTriggerPattern})$' || true)
if [ -n "$NOTICE_TRIGGER" ] && [ -n "$UNSTAGED_TRIGGER" ]; then
    echo "[notices hook] Refusing to refresh notices with unstaged trigger inputs." >&2
    echo "[notices hook] Stage, stash, or discard those changes, then retry." >&2
    exit 1
fi
if [ -n "$NOTICE_TRIGGER" ]; then
    echo "[notices hook] Refreshing third-party notices before commit..." >&2
    ${noticesManualCommand}
    git add -- ${noticesTrackedOutput}
fi

run_staged
`

export const commitMessageHookContent = (): string => `#!/bin/sh
# ${commitMessageHookMarker}: commit-msg
if ! awk '
  /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
  {
    count += 1
    subject = $0
  }
  END {
    validTypes = "(build|chore|ci|docs|feat|fix|perf|refactor|revert|security|style|test)"
    exit !(count == 1 && subject ~ ("^" validTypes ": [^[:space:]].*$"))
  }
' "$1"; then
  echo "Commit message must be one Conventional Commit subject without a scope: <type>: <subject>." >&2
  exit 1
fi
`

export const installThirdPartyNoticesHook = (root = repoRoot): void => {
  assertVitePlusHooksInstalled(root)

  const paths = createNoticeHookPaths(root)

  mkdirSync(paths.hooksRoot, { recursive: true })
  writeFileSync(paths.commitMessageHook, commitMessageHookContent(), { mode: 0o755 })
  writeFileSync(paths.preCommitHook, preCommitHookContent(), { mode: 0o755 })
  chmodSync(paths.commitMessageHook, 0o755)
  chmodSync(paths.preCommitHook, 0o755)
  console.log('installed Vite+ commit hooks: .vite-hooks/commit-msg, .vite-hooks/pre-commit')
}

export const thirdPartyNoticesHookStatusChecks = (
  root = repoRoot,
): NoticeHookStatusCheck[] => {
  const paths = createNoticeHookPaths(root)
  const commitMessageContent = readTextIfExists(paths.commitMessageHook)
  const preCommitContent = readTextIfExists(paths.preCommitHook)

  return [
    {
      ok: existsSync(paths.preCommitDispatcher),
      text: '.vite-hooks/_/pre-commit dispatcher exists',
    },
    {
      ok: commitMessageContent.includes(commitMessageHookMarker),
      text: '.vite-hooks/commit-msg contains Conventional Commit marker',
    },
    {
      ok: commitMessageContent.includes('one Conventional Commit subject without a scope'),
      text: '.vite-hooks/commit-msg enforces one scoped-free Conventional Commit subject',
    },
    {
      ok: preCommitContent.includes(noticesHookMarker),
      text: '.vite-hooks/pre-commit contains third-party notice marker',
    },
    {
      ok: preCommitContent
        .split('\n')
        .some(line => line.trim() === noticesManualCommand),
      text: '.vite-hooks/pre-commit runs third-party notice generation',
    },
    {
      ok: preCommitContent.includes(`git add -- ${noticesTrackedOutput}`),
      text: '.vite-hooks/pre-commit stages THIRD_PARTY_NOTICES.md only',
    },
    {
      ok: noticesTriggerInputs.every(path => preCommitContent.includes(path)),
      text: '.vite-hooks/pre-commit lists every third-party notice trigger',
    },
  ]
}

const printStatusChecks = (checks: NoticeHookStatusCheck[]): void => {
  for (const check of checks) {
    console.log(`${check.ok ? 'ok' : 'not ok'} ${check.text}`)
  }
}

export const main = (argv = process.argv.slice(2)): void => {
  const [
    command,
  ] = argv

  if (command === 'install') {
    installThirdPartyNoticesHook()
    return
  }

  if (command === 'status') {
    const checks = thirdPartyNoticesHookStatusChecks()

    printStatusChecks(checks)
    if (checks.every(check => check.ok)) {
      return
    }

    process.exitCode = 1
    return
  }

  throw new Error('Usage: vp exec tsx scripts/install-third-party-notices-hook.ts <install|status>')
}

const isMainModule = (): boolean => (
  process.argv[1] !== undefined && resolve(process.argv[1]) === scriptPath
)

if (isMainModule()) {
  try {
    main()
  }
  catch (error) {
    const message = error instanceof Error ? error.message : String(error)

    console.error(message)
    process.exit(1)
  }
}
